Adding CONTRIBUTING.md file
redhat-beyond/Smarticle pull request #13
Opened 2022-11-10 17:48 UTC by finziamit

Adding CONTRIBUTING.md file
resolve #11

2022-11-10 18:00 UTC, NitzanMordhai approved these changes
LGTM

2022-11-10 18:02 UTC, Anas-mhameed approved these changes

2022-11-10 18:12 UTC, Shalevro2 requested changes
Add a space between hashtags and headers text.

2022-11-10 18:12 UTC, Shalevro2 commented on CONTRIBUTING.md
> +#Contributing
I think you need to add a space after the hashtag for create a h1 header.

2022-11-10 18:12 UTC, Shalevro2 commented on CONTRIBUTING.md
> +##Pre-Requirements
Also here and in the rest of the file

2022-11-10 19:21 UTC, finziamit commented on CONTRIBUTING.md
> +##Pre-Requirements
done

2022-11-10 19:21 UTC, Anas-mhameed approved these changes

2022-11-10 19:22 UTC, avi-biton commented
1 - Please add space after the # (like @Shalevro2 commented)
2 - When you open the file, you can see that there are no new lines.
To add new line wherever you want, you need to insert 2 spaces at the end of the line, for example:
`this is one line  `
`this is the second line`
3 - If you want to use dots for sections (like: `•	Giving and gracefully accepting constructive feedback`), use `*` instead of copying the `•`
So this line for example will look like: `*	Giving and gracefully accepting constructive feedback`

Note for you all, almost every IDE (pycharm for example) has the option of md file preview, so you can see the result while you are writing the md file.
Other way is the link that @Shalevro2 added to the slack: https://markdownlivepreview.com/
you can also use https://www.markdownguide.org/cheat-sheet/ as a cheatsheet

2022-11-10 23:16 UTC, Shalevro2 approved these changes
LGTM

2022-11-11 04:01 UTC, Anas-mhameed approved these changes

2022-11-11 06:57 UTC, avi-biton commented on CONTRIBUTING.md
> +Instances of abusive, harassing, or otherwise unacceptable behavior may be reported to the community leaders responsible for enforcement at Smarticle@walla.co.il. All complaints will be reviewed and
Is Smarticle@walla.co.il an actual mail? does it really exist?

2022-11-11 07:14 UTC, merged